from datetime import datetime


def generate_report(kpis):

    report = f"""
RetailPulse AI Business Report
Generated On : {datetime.now().strftime("%d-%m-%Y %H:%M")}

----------------------------------------

Revenue : ₹{kpis['revenue']:,.2f}

Profit : ₹{kpis['profit']:,.2f}

Products Sold : {kpis['products_sold']}

Low Stock Products : {kpis['low_stock']}

----------------------------------------

Generated by RetailPulse AI
"""

    return report